all: main.cpp
	g++ -o main main.cpp -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs
build: main.cpp
	g++ -o main main.cpp -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs
clean: 
	rm -f main
	
