all: main.cpp
	g++ -o main main.cpp -lopencv_core -lopencv_highgui -lopencv_imgcodecs
	./main
build: main.cpp
	g++ -o main main.cpp -lopencv_core -lopencv_highgui -lopencv_imgcodecs
clean: 
	rm -f main
	
